-- Auto-generated by Matugen

require('base16-colorscheme').setup({
  base00 = '#091518', -- 背景
  base01 = '#051013', --较浅的背景色
  base02 = '#121d21',
  base03 = '#00d9fd', -- 键盘字符，匹配大括号
  base04 = '#bcc9cd',
  base05 = '#00d9fd', -- 括号，运算符
  base06 = '#273236',
  base07 = '#2f3b3f',

  base08 = '#a5caf5',-- 变量名
  base09 = '#c4e7ff', -- 整数、布尔值 (True/False)。
  base0A = '#a8cbe2', --类名 (Class)、搜索匹配到的背景
  base0B = '#00d9fd', -- 字符串
  base0C = '#a5caf5',
  base0D = '#004e5c', -- 函数名
  base0E = '#a8cbe2', -- 关键词 (if, else, return, import)。
  base0F = '#ffb4ab',
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#d8e5e9', -- 选中文字背景
  fg = '#091518', -- 选中文字颜色
})

set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#869397', -- 注释
})

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#a5caf5',
})

set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#a8cbe2',
})

vim.api.nvim_set_hl(0, 'Keyword', {
  fg = '#00687a',
})

vim.api.nvim_set_hl(0, 'MsgArea', {
  bg = '#162125', --底边
  fg = '#00d9fd',
})
