-- Auto-generated by Matugen

require('base16-colorscheme').setup({
  base00 = '#0f1416', -- 背景
  base01 = '#0a0f11', --较浅的背景色
  base02 = '#171c1f',
  base03 = '#88d1ec', -- 键盘字符，匹配大括号
  base04 = '#bfc8cc',
  base05 = '#88d1ec', -- 括号，运算符
  base06 = '#2c3134',
  base07 = '#353a3c',

  base08 = '#c3c3eb',-- 变量名
  base09 = '#cfe6f1', -- 整数、布尔值 (True/False)。
  base0A = '#b3cad4', --类名 (Class)、搜索匹配到的背景
  base0B = '#88d1ec', -- 字符串
  base0C = '#c3c3eb',
  base0D = '#004e61', -- 函数名
  base0E = '#b3cad4', -- 关键词 (if, else, return, import)。
  base0F = '#ffb4ab',
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#dee3e6', -- 选中文字背景
  fg = '#0f1416', -- 选中文字颜色
})

set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#8a9296', -- 注释
})

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#c3c3eb',
})

set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#b3cad4',
})

vim.api.nvim_set_hl(0, 'Keyword', {
  fg = '#07677f',
})

vim.api.nvim_set_hl(0, 'MsgArea', {
  bg = '#1b2023', --底边
  fg = '#88d1ec',
})
