-- Auto-generated by Matugen

require('base16-colorscheme').setup({
  base00 = '#111318', -- 背景
  base01 = '#0c0e13', --较浅的背景色
  base02 = '#191c20',
  base03 = '#a7c8ff', -- 键盘字符，匹配大括号
  base04 = '#c4c6cf',
  base05 = '#a7c8ff', -- 括号，运算符
  base06 = '#2e3035',
  base07 = '#37393e',

  base08 = '#dbbce1',-- 变量名
  base09 = '#d9e3f8', -- 整数、布尔值 (True/False)。
  base0A = '#bdc7dc', --类名 (Class)、搜索匹配到的背景
  base0B = '#a7c8ff', -- 字符串
  base0C = '#dbbce1',
  base0D = '#244777', -- 函数名
  base0E = '#bdc7dc', -- 关键词 (if, else, return, import)。
  base0F = '#ffb4ab',
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#e1e2e9', -- 选中文字背景
  fg = '#111318', -- 选中文字颜色
})

set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#8e9199', -- 注释
})

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#dbbce1',
})

set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#bdc7dc',
})

vim.api.nvim_set_hl(0, 'Keyword', {
  fg = '#3e5f90',
})

vim.api.nvim_set_hl(0, 'MsgArea', {
  bg = '#1d2024', --底边
  fg = '#a7c8ff',
})
